### ISSUE TITLE
something is wrong with the `zerocracy-vitals`

### ISSUE THREAD

**Issue by Suban05** [zerocracy/pages-action#138]
@yegor256 something is wrong with the `zerocracy-vitals`, and I don't understand, what.

The last payout was on 26.08.24
![2024-09-24 23-34-25](https://github.com/user-attachments/assets/1903c124-e66a-4921-82ca-dc3f4a24c6b2)

and starting from the 35th week (29.08.24), the system incorrectly counts the total points:
![2024-09-24 23-21-30](https://github.com/user-attachments/assets/ed1b8c94-38b2-41ed-9117-73d3d7acabde)

for example for the `pay` column:
the first position should be equal to 123 points
the second position should be 170
the third position should be 28 

also I'm not sure about the `run` column

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.36`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.36`

**Comment by yegor256** [comment]
@rultor status

**Comment by 0crat** [comment]
@Suban05 Hello! Thank you for reporting a new bug. As per our team's policy, you've earned **8** points for this contribution. Your diligence in identifying issues helps improve our project's quality. Your current balance is now [+126](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Please continue to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) any other issues you may find in the repository that [don't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) up to standard. Your efforts are greatly appreciated!

**Comment by yegor256** [comment]
@Suban05 I believe, it's fixed, please check

**Comment by Suban05** [comment]
@yegor256 yes, it's fixed, great job! thanks!
